import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import com.sportsinventory.DTO.UserDTO;
import com.sportsinventory.DAO.UserDAO;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author strix
 */
public class AddUser extends javax.swing.JFrame {

    /**
     * Creates new form AddUser
     */
    public boolean flag1 = false;
    public boolean flag2 = false;
    public AdminMainPage admin;
    public AddUser() {
        initComponents();
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("d MMM YYY");  
        LocalDateTime now = LocalDateTime.now();  
        String borrowDateString = dtf.format(now);
        CreatedDateField.setText(borrowDateString);
    }
    
    public AddUser(AdminMainPage _admin) {
        initComponents();
        admin = _admin;
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("d MMM YYY");  
        LocalDateTime now = LocalDateTime.now();  
        String borrowDateString = dtf.format(now);
        CreatedDateField.setText(borrowDateString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        studentIDText = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        studentNameText = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        studentEmailText = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        accountCreateDate = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        CohortText = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        studentID = new javax.swing.JTextField();
        CreatedDateField = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        studentEmail = new javax.swing.JTextField();
        studentName = new javax.swing.JTextField();
        CohortSelection = new javax.swing.JComboBox<>();
        majorSelection = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add User");
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(150, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(150, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 300));

        jPanel2.setBackground(new java.awt.Color(23, 35, 51));
        jPanel2.setMaximumSize(new java.awt.Dimension(150, 40));
        jPanel2.setMinimumSize(new java.awt.Dimension(150, 40));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(150, 40));

        studentIDText.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        studentIDText.setForeground(new java.awt.Color(255, 255, 255));
        studentIDText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentIDText.setText("Student ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentIDText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentIDText, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(23, 35, 51));
        jPanel7.setMaximumSize(new java.awt.Dimension(150, 40));
        jPanel7.setMinimumSize(new java.awt.Dimension(150, 40));
        jPanel7.setName(""); // NOI18N
        jPanel7.setPreferredSize(new java.awt.Dimension(150, 40));

        studentNameText.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        studentNameText.setForeground(new java.awt.Color(255, 255, 255));
        studentNameText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentNameText.setText("Student Name");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(23, 35, 51));
        jPanel8.setMaximumSize(new java.awt.Dimension(150, 40));
        jPanel8.setMinimumSize(new java.awt.Dimension(150, 40));
        jPanel8.setName(""); // NOI18N
        jPanel8.setPreferredSize(new java.awt.Dimension(150, 40));

        studentEmailText.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        studentEmailText.setForeground(new java.awt.Color(255, 255, 255));
        studentEmailText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentEmailText.setText("Student Email");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentEmailText, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentEmailText, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(23, 35, 51));
        jPanel9.setMaximumSize(new java.awt.Dimension(150, 40));
        jPanel9.setMinimumSize(new java.awt.Dimension(150, 40));
        jPanel9.setName(""); // NOI18N
        jPanel9.setPreferredSize(new java.awt.Dimension(150, 40));

        accountCreateDate.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        accountCreateDate.setForeground(new java.awt.Color(255, 255, 255));
        accountCreateDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountCreateDate.setText("Create Date");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(accountCreateDate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountCreateDate, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(23, 35, 51));
        jPanel10.setMaximumSize(new java.awt.Dimension(150, 40));
        jPanel10.setMinimumSize(new java.awt.Dimension(150, 40));
        jPanel10.setName(""); // NOI18N
        jPanel10.setPreferredSize(new java.awt.Dimension(150, 40));

        CohortText.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        CohortText.setForeground(new java.awt.Color(255, 255, 255));
        CohortText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CohortText.setText("Cohort - College");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CohortText, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CohortText, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 0));
        jPanel4.setMaximumSize(new java.awt.Dimension(150, 40));
        jPanel4.setMinimumSize(new java.awt.Dimension(150, 40));
        jPanel4.setName(""); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(150, 40));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(51, 204, 0));
        jPanel3.setMaximumSize(new java.awt.Dimension(250, 300));
        jPanel3.setMinimumSize(new java.awt.Dimension(250, 300));
        jPanel3.setPreferredSize(new java.awt.Dimension(250, 300));

        studentID.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        studentID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        studentID.setText("V");
        studentID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                studentIDFocusLost(evt);
            }
        });
        studentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDActionPerformed(evt);
            }
        });
        studentID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                studentIDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                studentIDKeyTyped(evt);
            }
        });

        CreatedDateField.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        CreatedDateField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CreatedDateField.setText("Current Time/date");

        confirmButton.setFont(new java.awt.Font("Helvetica Neue", 0, 30)); // NOI18N
        confirmButton.setText("Confirm");
        confirmButton.setMaximumSize(new java.awt.Dimension(100, 30));
        confirmButton.setMinimumSize(new java.awt.Dimension(100, 30));
        confirmButton.setPreferredSize(new java.awt.Dimension(100, 30));
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        studentEmail.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        studentEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        studentEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                studentEmailFocusLost(evt);
            }
        });
        studentEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentEmailActionPerformed(evt);
            }
        });
        studentEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                studentEmailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                studentEmailKeyTyped(evt);
            }
        });

        studentName.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        studentName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        studentName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                studentNameFocusLost(evt);
            }
        });
        studentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentNameActionPerformed(evt);
            }
        });
        studentName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                studentNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                studentNameKeyTyped(evt);
            }
        });

        CohortSelection.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        CohortSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cohort 1", "Cohort 2", "Cohort 3", "Cohort 4" }));

        majorSelection.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        majorSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CECS", "CBM", "CHS", "CAS", "Staff" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreatedDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(studentID, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(studentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CohortSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(majorSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(studentID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(studentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(CreatedDateField)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(majorSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CohortSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 250, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_studentIDActionPerformed

    private void studentIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDKeyReleased

    private void studentIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentIDKeyTyped
        // TODO add your handling code here:
        //checking to have no character

    }//GEN-LAST:event_studentIDKeyTyped

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        String IDString = studentID.getText();
        IDString = IDString.substring(1, IDString.length());
        
        int studentIDString = Integer.parseInt(IDString);
        String studentNameString = studentName.getText();
        String studentEmailString = studentEmail.getText();
        String createdDate = CreatedDateField.getText();
        String cohortString = CohortSelection.getSelectedItem().toString();
        System.err.println(cohortString);
        String major = majorSelection.getSelectedItem().toString();
        
        UserDTO user = new UserDTO();
        user.setUserID(studentIDString);
        user.setEmail(studentEmailString);
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("YYY-MM-dd");  
        LocalDateTime now = LocalDateTime.now();  
        String regDate = dtf.format(now);
        user.setRegDate(regDate);
        
        user.setFullName(studentNameString);
        
        String[] arr = studentNameString.split(" ");
        String usrName = arr[arr.length - 1];
        user.setUsername(usrName);
        user.setPassword(usrName);
        user.setCohort(cohortString);
        user.setMajor(major);
        
        new UserDAO().addFunction(user);
        if(flag1 && flag2)
        {
            admin.userButtonPressSom();
            super.dispose();
        }
        
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void studentIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentIDFocusLost
        // TODO add your handling code here:
        flag1 = false;
        String text = studentID.getText();
       
        if(text.charAt(0) != 'V')
        {
            JOptionPane.showMessageDialog(null, "StudentID must starts with V!");
        }
        else if(text.length() != 10)
        {
            JOptionPane.showMessageDialog(null, "StudentID is not correct!");
        }
        else if(!text.substring( 1, 5).equals("2020") && !text.substring( 1, 5).equals("2021") && !text.substring( 1, 5).equals("2022"))
        {
            JOptionPane.showMessageDialog(null, "StudentID is not correct!");
        }
        else{
            flag1 = true;
        }
        
    }//GEN-LAST:event_studentIDFocusLost

    private void studentEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentEmailFocusLost
        // TODO add your handling code here:
        flag2 = false;
        String text = studentEmail.getText();
        if(!text.endsWith("@vinuni.edu.vn") )
        {
            JOptionPane.showMessageDialog(null, "The email must ends with @vinuni.edu.vn");
        }
        else{
            flag2 = true;
        }
    }//GEN-LAST:event_studentEmailFocusLost

    private void studentEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentEmailActionPerformed

    private void studentEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentEmailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_studentEmailKeyReleased

    private void studentEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentEmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_studentEmailKeyTyped

    private void studentNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_studentNameFocusLost

    private void studentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentNameActionPerformed

    private void studentNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_studentNameKeyReleased

    private void studentNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_studentNameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CohortSelection;
    private javax.swing.JLabel CohortText;
    private javax.swing.JLabel CreatedDateField;
    private javax.swing.JLabel accountCreateDate;
    private javax.swing.JButton confirmButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JComboBox<String> majorSelection;
    private javax.swing.JTextField studentEmail;
    private javax.swing.JLabel studentEmailText;
    private javax.swing.JTextField studentID;
    private javax.swing.JLabel studentIDText;
    private javax.swing.JTextField studentName;
    private javax.swing.JLabel studentNameText;
    // End of variables declaration//GEN-END:variables
}
