/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author strix
 */
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime;    
import com.toedter.calendar.JDateChooser;
import javax.swing.JOptionPane;
import com.sportsinventory.DAO.BookingDAO;
import com.sportsinventory.DTO.BookingDTO;
import com.sportsinventory.DAO.ItemDAO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
public class Confirmation extends javax.swing.JFrame {

    /**
     * Creates new form Confirmation
     */
    public int maxQuantity = 0;
    public int itemIDString = 0;
    public String itemNameString = "";
    public int userID = 0;
    public AtheleteMainPage athelete;
    public Confirmation()
    {
        initComponents();
    }
    public Confirmation(String itemName, String ID, String stock, int _userID, AtheleteMainPage _athelete) {
        initComponents();
        dateChooser.setDateFormatString("YYY-MM-dd");
        // change item name, item id here
        ItemIDLabel.setText(ID);
        ItemNameLabel.setText(itemName);
        itemNameString = itemName;
        itemIDString = Integer.parseInt(ID);
        maxQuantity = Integer.parseInt(stock);
        userID = _userID;
        athelete = _athelete;
        
        // update borrow Date
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("YYY-MM-dd ");  
        LocalDateTime now = LocalDateTime.now();  
        String borrowDateString = dtf.format(now);
        BorrowDateField.setText(borrowDateString);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        itemIDText = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        itemNameText = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        QuantityTetx = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        BorrowDateTetx = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        ReturnDateText = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        QuantityTextField = new javax.swing.JTextField();
        BorrowDateField = new javax.swing.JLabel();
        ItemNameLabel = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        ItemIDLabel = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(150, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(150, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 300));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(23, 35, 51));
        jPanel2.setMaximumSize(new java.awt.Dimension(150, 32));
        jPanel2.setMinimumSize(new java.awt.Dimension(150, 32));
        jPanel2.setPreferredSize(new java.awt.Dimension(150, 32));

        itemIDText.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        itemIDText.setForeground(new java.awt.Color(255, 255, 255));
        itemIDText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemIDText.setText("Item ID");
        itemIDText.setMaximumSize(new java.awt.Dimension(100, 20));
        itemIDText.setMinimumSize(new java.awt.Dimension(100, 20));
        itemIDText.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(itemIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(itemIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel7.setBackground(new java.awt.Color(23, 35, 51));
        jPanel7.setMaximumSize(new java.awt.Dimension(150, 32));
        jPanel7.setMinimumSize(new java.awt.Dimension(150, 32));
        jPanel7.setPreferredSize(new java.awt.Dimension(150, 32));

        itemNameText.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        itemNameText.setForeground(new java.awt.Color(255, 255, 255));
        itemNameText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemNameText.setText("Item Name");
        itemNameText.setMaximumSize(new java.awt.Dimension(100, 20));
        itemNameText.setMinimumSize(new java.awt.Dimension(100, 20));
        itemNameText.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(itemNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(itemNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jPanel8.setBackground(new java.awt.Color(23, 35, 51));
        jPanel8.setMaximumSize(new java.awt.Dimension(150, 32));
        jPanel8.setMinimumSize(new java.awt.Dimension(150, 32));
        jPanel8.setPreferredSize(new java.awt.Dimension(150, 32));

        QuantityTetx.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        QuantityTetx.setForeground(new java.awt.Color(255, 255, 255));
        QuantityTetx.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QuantityTetx.setText("Quantity");
        QuantityTetx.setMaximumSize(new java.awt.Dimension(100, 20));
        QuantityTetx.setMinimumSize(new java.awt.Dimension(100, 20));
        QuantityTetx.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(QuantityTetx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QuantityTetx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jPanel9.setBackground(new java.awt.Color(23, 35, 51));
        jPanel9.setMaximumSize(new java.awt.Dimension(150, 32));
        jPanel9.setMinimumSize(new java.awt.Dimension(150, 32));
        jPanel9.setPreferredSize(new java.awt.Dimension(150, 32));

        BorrowDateTetx.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        BorrowDateTetx.setForeground(new java.awt.Color(255, 255, 255));
        BorrowDateTetx.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BorrowDateTetx.setText("Borrow Date");
        BorrowDateTetx.setMaximumSize(new java.awt.Dimension(100, 20));
        BorrowDateTetx.setMinimumSize(new java.awt.Dimension(100, 20));
        BorrowDateTetx.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(BorrowDateTetx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BorrowDateTetx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        jPanel10.setBackground(new java.awt.Color(23, 35, 51));
        jPanel10.setMaximumSize(new java.awt.Dimension(150, 32));
        jPanel10.setMinimumSize(new java.awt.Dimension(150, 32));
        jPanel10.setPreferredSize(new java.awt.Dimension(150, 32));

        ReturnDateText.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        ReturnDateText.setForeground(new java.awt.Color(255, 255, 255));
        ReturnDateText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReturnDateText.setText("Return Date");
        ReturnDateText.setMaximumSize(new java.awt.Dimension(100, 20));
        ReturnDateText.setMinimumSize(new java.awt.Dimension(100, 20));
        ReturnDateText.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(ReturnDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ReturnDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 150, -1));

        jPanel4.setBackground(new java.awt.Color(0, 153, 0));
        jPanel4.setMaximumSize(new java.awt.Dimension(150, 40));
        jPanel4.setMinimumSize(new java.awt.Dimension(150, 40));
        jPanel4.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 244, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 300));

        QuantityTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        QuantityTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        QuantityTextField.setText("0");
        QuantityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityTextFieldActionPerformed(evt);
            }
        });
        QuantityTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                QuantityTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                QuantityTextFieldKeyTyped(evt);
            }
        });

        BorrowDateField.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        BorrowDateField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BorrowDateField.setText("Current Time/date");

        ItemNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        ItemNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemNameLabel.setText("Name from DB");

        confirmButton.setBackground(new java.awt.Color(0, 204, 0));
        confirmButton.setFont(new java.awt.Font("Helvetica Neue", 0, 30)); // NOI18N
        confirmButton.setText("Confirm");
        confirmButton.setMaximumSize(new java.awt.Dimension(100, 30));
        confirmButton.setMinimumSize(new java.awt.Dimension(100, 30));
        confirmButton.setPreferredSize(new java.awt.Dimension(100, 30));
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        ItemIDLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        ItemIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemIDLabel.setText("ID from DB");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ItemNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(confirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(BorrowDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(ItemIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(QuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(ItemIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ItemNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(QuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(BorrowDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 240, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        String dateBorrowString = BorrowDateField.getText();
        String dateReturnString = dateChooser.getDate().toString();
        int quantityInt = Integer.parseInt(QuantityTextField.getText());
        if(quantityInt > maxQuantity)
        {
            JOptionPane.showMessageDialog(null, "Maximum quantity is " + maxQuantity);
            return;
        }
        else if(dateReturnString.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Enter Return Date");
        }
        else
        {
            try {
                ResultSet rs = new BookingDAO().getLastRow();
                int bookingID = 100;
                try {
                    if (rs.next()) {
                        bookingID = rs.getInt("bookingID") + 1;
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Confirmation.class.getName()).log(Level.SEVERE, null, ex);
                }
                new BookingDAO().addBookingDAO(bookingID, userID, itemIDString, dateBorrowString, dateBorrowString, "borrowing", quantityInt);
                
                ResultSet rs2 = new ItemDAO().getItemIDRow(itemIDString);
                int quantityLeft = 0;
                if (rs2.next()) {
                    quantityLeft = rs2.getInt("quantity") - quantityInt;
                }
                
                new ItemDAO().updateQuantity(quantityLeft, itemIDString);
                
                athelete.inventoryButtonPressSim();
                
                super.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(Confirmation.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void QuantityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_QuantityTextFieldActionPerformed

    private void QuantityTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantityTextFieldKeyTyped
        // TODO add your handling code here:
        //checking to have no character
        
        
    }//GEN-LAST:event_QuantityTextFieldKeyTyped

    private void QuantityTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantityTextFieldKeyReleased
        // TODO add your handling code here:
        String text = QuantityTextField.getText();
        
        text = text.replaceAll("\\D","");
        if(text.length() == 0) 
        {
            QuantityTextField.setText("");
        }
        else if(text.length() > 3){
            QuantityTextField.setText(String.valueOf(Integer.parseInt( text.substring(0, 3))));
        }
        else{
            QuantityTextField.setText(String.valueOf(Integer.parseInt( text)));
        }
    }//GEN-LAST:event_QuantityTextFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Confirmation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BorrowDateField;
    private javax.swing.JLabel BorrowDateTetx;
    private javax.swing.JLabel ItemIDLabel;
    private javax.swing.JLabel ItemNameLabel;
    private javax.swing.JLabel QuantityTetx;
    private javax.swing.JTextField QuantityTextField;
    private javax.swing.JLabel ReturnDateText;
    private javax.swing.JButton confirmButton;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel itemIDText;
    private javax.swing.JLabel itemNameText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
